### ISSUE TITLE
Where is the "main.py"?

### ISSUE THREAD

**Issue by Junxin-Huo** [sugyan/face-generator#2]
In "README.md", Usage - training: "python main.py".
What I am confused is where I can find the file to run. There isn't a file named "main.py".

**Comment by sugyan** [comment]
I'm sorry, `main.py` is renamed to `train.py`.
I updated `README.md`.
Now I'm just rewriting the code in this repository.

**Comment by Junxin-Huo** [comment]
Thanks.
